let scores = [];

const addPersoonlijkeScore = (student, assignment, difficultGrade, niceGrade) =>
  scores.push({
    student: student,
    assignment: assignment,
    difficultGrade: difficultGrade,
    niceGrade: niceGrade,
  });

addPersoonlijkeScore("Evelyn", "SCRUM", 3, 4);
addPersoonlijkeScore("Evelyn", "W1D1-1", 3, 3);
addPersoonlijkeScore("Evelyn", "W1D2-1", 1, 3);
addPersoonlijkeScore("Evelyn", "W1D2-2", 1, 4);
addPersoonlijkeScore("Evelyn", "W1D2-3", 2, 3);
addPersoonlijkeScore("Evelyn", "W1D2-4", 3, 4);
addPersoonlijkeScore("Evelyn", "W1D2-5", 3, 4);
addPersoonlijkeScore("Evelyn", "W1D3-1", 3, 4);
addPersoonlijkeScore("Evelyn", "W1D3-2", 3, 4);
addPersoonlijkeScore("Evelyn", "W1D3-4", 4, 4);
addPersoonlijkeScore("Evelyn", "W1D3-5", 4, 4);
addPersoonlijkeScore("Evelyn", "W1D3 - Project - Guess-the-number", 5, 5);
addPersoonlijkeScore("Evelyn", "W1D4-1", 4, 5);
addPersoonlijkeScore("Evelyn", "W1D4 - Project - Kleurentoggle", 3, 4);
addPersoonlijkeScore("Evelyn", "W1D5 - Project - Galgje", 3, 3);
addPersoonlijkeScore("Evelyn", "W2D1-1", 1, 5);
addPersoonlijkeScore("Evelyn", "W2D1-2", 2, 5);
addPersoonlijkeScore("Evelyn", "W2D2-1", 3, 4);
addPersoonlijkeScore("Evelyn", "W2D2-2", 3, 4);
addPersoonlijkeScore("Evelyn", "W2D2-3", 3, 4);
addPersoonlijkeScore("Evelyn", "W2D3-1", 4, 4);
addPersoonlijkeScore("Evelyn", "W2D3-2", 1, 3);
addPersoonlijkeScore("Evelyn", "W2D3-3", 4, 4);
addPersoonlijkeScore("Evelyn", "W2D4-1", 1, 3);
addPersoonlijkeScore("Evelyn", "W2D4-2", 4, 4);
addPersoonlijkeScore("Evelyn", "W2D4-3", 1, 3);
addPersoonlijkeScore("Evelyn", "W2D5 - Project - Filmzoeker", 3, 4);
addPersoonlijkeScore("Evelyn", "W3D1-1", 3, 4);
addPersoonlijkeScore("Evelyn", "W3D1-2", 2, 4);
addPersoonlijkeScore("Evelyn", "W3D1-3", 3, 4);
addPersoonlijkeScore("Evelyn", "W3D1-4", 3, 3);
addPersoonlijkeScore("Evelyn", "W3D2-1", 2, 4);
addPersoonlijkeScore("Evelyn", "W3D2-2", 3, 3);
addPersoonlijkeScore("Evelyn", "W3D2-3", 3, 5);
addPersoonlijkeScore("Evelyn", "W3D3-1", 4, 4);
addPersoonlijkeScore("Evelyn", "W3D3-2", 4, 5);
addPersoonlijkeScore("Evelyn", "W3D3-3", 3, 5);
addPersoonlijkeScore("Evelyn", "W3D3-4", 4, 5);
addPersoonlijkeScore("Evelyn", "W3D4-1", 5, 5);
addPersoonlijkeScore("Evelyn", "W3D4-2", 1, 5);
addPersoonlijkeScore("Evelyn", "W3D5 - Project - Todo-List", 2, 5);
addPersoonlijkeScore("Evelyn", "W4D2-1", 1, 5);
addPersoonlijkeScore("Evelyn", "W4D2-2", 1, 5);
addPersoonlijkeScore("Evelyn", "W4D2-3", 1, 5);
addPersoonlijkeScore("Evelyn", "W4D2-4", 1, 5);
addPersoonlijkeScore("Evelyn", "W4D3-1", 1, 5);
addPersoonlijkeScore("Evelyn", "W4D3-2", 1, 5);
addPersoonlijkeScore("Evelyn", "W4D3-3", 1, 5);
addPersoonlijkeScore("Evelyn", "W4D3-4", 1, 5);
addPersoonlijkeScore("Evelyn", "W4D3-5", 1, 5);
addPersoonlijkeScore("Evelyn", "W4D3 - Project - Next-Level CSS", 1, 5);
addPersoonlijkeScore("Evelyn", "W5D4-1", 3, 4);
addPersoonlijkeScore("Evelyn", "W5D5 - Project - Lil_Playlist", 4, 3);
addPersoonlijkeScore("Evelyn", "W6D1-1", 5, 5);
addPersoonlijkeScore("Evelyn", "W6D2-1", 4, 3);
addPersoonlijkeScore("Evelyn", "W6D2 - Project - Eindopdracht", 5, 5);
addPersoonlijkeScore("Aranka", "SCRUM", 1, 1);
addPersoonlijkeScore("Aranka", "W1D1-1", 4, 3);
addPersoonlijkeScore("Aranka", "W1D2-1", 3, 1);
addPersoonlijkeScore("Aranka", "W1D2-2", 3, 2);
addPersoonlijkeScore("Aranka", "W1D2-3", 4, 1);
addPersoonlijkeScore("Aranka", "W1D2-4", 2, 3);
addPersoonlijkeScore("Aranka", "W1D2-5", 4, 2);
addPersoonlijkeScore("Aranka", "W1D3-1", 3, 2);
addPersoonlijkeScore("Aranka", "W1D3-2", 2, 1);
addPersoonlijkeScore("Aranka", "W1D3-4", 1, 2);
addPersoonlijkeScore("Aranka", "W1D3-5", 4, 1);
addPersoonlijkeScore("Aranka", "W1D3 - Project - Guess-the-number", 2, 3);
addPersoonlijkeScore("Aranka", "W1D4-1", 3, 2);
addPersoonlijkeScore("Aranka", "W1D4 - Project - Kleurentoggle", 4, 3);
addPersoonlijkeScore("Aranka", "W1D5 - Project - Galgje", 4, 1);
addPersoonlijkeScore("Aranka", "W2D1-1", 2, 4);
addPersoonlijkeScore("Aranka", "W2D1-2", 4, 4);
addPersoonlijkeScore("Aranka", "W2D2-1", 3, 4);
addPersoonlijkeScore("Aranka", "W2D2-2", 3, 4);
addPersoonlijkeScore("Aranka", "W2D2-3", 1, 4);
addPersoonlijkeScore("Aranka", "W2D3-1", 4, 3);
addPersoonlijkeScore("Aranka", "W2D3-2", 4, 1);
addPersoonlijkeScore("Aranka", "W2D3-3", 1, 1);
addPersoonlijkeScore("Aranka", "W2D4-1", 1, 4);
addPersoonlijkeScore("Aranka", "W2D4-2", 2, 3);
addPersoonlijkeScore("Aranka", "W2D4-3", 2, 3);
addPersoonlijkeScore("Aranka", "W2D5 - Project - Filmzoeker", 2, 2);
addPersoonlijkeScore("Aranka", "W3D1-1", 4, 2);
addPersoonlijkeScore("Aranka", "W3D1-2", 3, 2);
addPersoonlijkeScore("Aranka", "W3D1-3", 1, 4);
addPersoonlijkeScore("Aranka", "W3D1-4", 1, 3);
addPersoonlijkeScore("Aranka", "W3D2-1", 1, 3);
addPersoonlijkeScore("Aranka", "W3D2-2", 2, 3);
addPersoonlijkeScore("Aranka", "W3D2-3", 2, 3);
addPersoonlijkeScore("Aranka", "W3D3-1", 2, 2);
addPersoonlijkeScore("Aranka", "W3D3-2", 4, 3);
addPersoonlijkeScore("Aranka", "W3D3-3", 3, 3);
addPersoonlijkeScore("Aranka", "W3D3-4", 1, 3);
addPersoonlijkeScore("Aranka", "W3D4-1", 1, 1);
addPersoonlijkeScore("Aranka", "W3D4-2", 3, 2);
addPersoonlijkeScore("Aranka", "W3D5 - Project - Todo-List", 1, 1);
addPersoonlijkeScore("Aranka", "W4D2-1", 2, 1);
addPersoonlijkeScore("Aranka", "W4D2-2", 3, 2);
addPersoonlijkeScore("Aranka", "W4D2-3", 2, 2);
addPersoonlijkeScore("Aranka", "W4D2-4", 3, 4);
addPersoonlijkeScore("Aranka", "W4D3-1", 2, 1);
addPersoonlijkeScore("Aranka", "W4D3-2", 4, 4);
addPersoonlijkeScore("Aranka", "W4D3-3", 3, 1);
addPersoonlijkeScore("Aranka", "W4D3-4", 3, 1);
addPersoonlijkeScore("Aranka", "W4D3-5", 4, 3);
addPersoonlijkeScore("Aranka", "W4D3 - Project - Next-Level CSS", 4, 4);
addPersoonlijkeScore("Aranka", "W5D4-1", 1, 3);
addPersoonlijkeScore("Aranka", "W5D5 - Project - Lil_Playlist", 3, 2);
addPersoonlijkeScore("Aranka", "W6D1-1", 1, 1);
addPersoonlijkeScore("Aranka", "W6D2-1", 2, 2);
addPersoonlijkeScore("Aranka", "W6D2 - Project - Eindopdracht", 3, 4);
addPersoonlijkeScore("Floris", "SCRUM", 2, 1);
addPersoonlijkeScore("Floris", "W1D1-1", 4, 3);
addPersoonlijkeScore("Floris", "W1D2-1", 1, 2);
addPersoonlijkeScore("Floris", "W1D2-2", 1, 4);
addPersoonlijkeScore("Floris", "W1D2-3", 1, 4);
addPersoonlijkeScore("Floris", "W1D2-4", 3, 4);
addPersoonlijkeScore("Floris", "W1D2-5", 1, 3);
addPersoonlijkeScore("Floris", "W1D3-1", 2, 4);
addPersoonlijkeScore("Floris", "W1D3-2", 4, 4);
addPersoonlijkeScore("Floris", "W1D3-4", 4, 2);
addPersoonlijkeScore("Floris", "W1D3-5", 2, 4);
addPersoonlijkeScore("Floris", "W1D3 - Project - Guess-the-number", 2, 2);
addPersoonlijkeScore("Floris", "W1D4-1", 1, 3);
addPersoonlijkeScore("Floris", "W1D4 - Project - Kleurentoggle", 4, 3);
addPersoonlijkeScore("Floris", "W1D5 - Project - Galgje", 4, 4);
addPersoonlijkeScore("Floris", "W2D1-1", 2, 2);
addPersoonlijkeScore("Floris", "W2D1-2", 4, 1);
addPersoonlijkeScore("Floris", "W2D2-1", 4, 1);
addPersoonlijkeScore("Floris", "W2D2-2", 2, 2);
addPersoonlijkeScore("Floris", "W2D2-3", 4, 2);
addPersoonlijkeScore("Floris", "W2D3-1", 1, 1);
addPersoonlijkeScore("Floris", "W2D3-2", 1, 2);
addPersoonlijkeScore("Floris", "W2D3-3", 3, 3);
addPersoonlijkeScore("Floris", "W2D4-1", 4, 4);
addPersoonlijkeScore("Floris", "W2D4-2", 3, 1);
addPersoonlijkeScore("Floris", "W2D4-3", 4, 1);
addPersoonlijkeScore("Floris", "W2D5 - Project - Filmzoeker", 4, 1);
addPersoonlijkeScore("Floris", "W3D1-1", 4, 3);
addPersoonlijkeScore("Floris", "W3D1-2", 2, 3);
addPersoonlijkeScore("Floris", "W3D1-3", 2, 3);
addPersoonlijkeScore("Floris", "W3D1-4", 3, 3);
addPersoonlijkeScore("Floris", "W3D2-1", 3, 2);
addPersoonlijkeScore("Floris", "W3D2-2", 2, 2);
addPersoonlijkeScore("Floris", "W3D2-3", 3, 2);
addPersoonlijkeScore("Floris", "W3D3-1", 4, 4);
addPersoonlijkeScore("Floris", "W3D3-2", 2, 4);
addPersoonlijkeScore("Floris", "W3D3-3", 2, 1);
addPersoonlijkeScore("Floris", "W3D3-4", 3, 2);
addPersoonlijkeScore("Floris", "W3D4-1", 1, 3);
addPersoonlijkeScore("Floris", "W3D4-2", 2, 2);
addPersoonlijkeScore("Floris", "W3D5 - Project - Todo-List", 4, 2);
addPersoonlijkeScore("Floris", "W4D2-1", 1, 4);
addPersoonlijkeScore("Floris", "W4D2-2", 2, 3);
addPersoonlijkeScore("Floris", "W4D2-3", 2, 4);
addPersoonlijkeScore("Floris", "W4D2-4", 1, 2);
addPersoonlijkeScore("Floris", "W4D3-1", 1, 4);
addPersoonlijkeScore("Floris", "W4D3-2", 4, 4);
addPersoonlijkeScore("Floris", "W4D3-3", 3, 2);
addPersoonlijkeScore("Floris", "W4D3-4", 2, 2);
addPersoonlijkeScore("Floris", "W4D3-5", 4, 1);
addPersoonlijkeScore("Floris", "W4D3 - Project - Next-Level CSS", 2, 2);
addPersoonlijkeScore("Floris", "W5D4-1", 1, 3);
addPersoonlijkeScore("Floris", "W5D5 - Project - Lil_Playlist", 3, 1);
addPersoonlijkeScore("Floris", "W6D1-1", 3, 2);
addPersoonlijkeScore("Floris", "W6D2-1", 1, 1);
addPersoonlijkeScore("Floris", "W6D2 - Project - Eindopdracht", 4, 1);
addPersoonlijkeScore("Hector", "SCRUM", 1, 2);
addPersoonlijkeScore("Hector", "W1D1-1", 1, 4);
addPersoonlijkeScore("Hector", "W1D2-1", 2, 4);
addPersoonlijkeScore("Hector", "W1D2-2", 2, 3);
addPersoonlijkeScore("Hector", "W1D2-3", 1, 2);
addPersoonlijkeScore("Hector", "W1D2-4", 1, 3);
addPersoonlijkeScore("Hector", "W1D2-5", 3, 1);
addPersoonlijkeScore("Hector", "W1D3-1", 1, 4);
addPersoonlijkeScore("Hector", "W1D3-2", 4, 3);
addPersoonlijkeScore("Hector", "W1D3-4", 3, 1);
addPersoonlijkeScore("Hector", "W1D3-5", 4, 2);
addPersoonlijkeScore("Hector", "W1D3 - Project - Guess-the-number", 3, 1);
addPersoonlijkeScore("Hector", "W1D4-1", 1, 1);
addPersoonlijkeScore("Hector", "W1D4 - Project - Kleurentoggle", 1, 3);
addPersoonlijkeScore("Hector", "W1D5 - Project - Galgje", 2, 4);
addPersoonlijkeScore("Hector", "W2D1-1", 4, 4);
addPersoonlijkeScore("Hector", "W2D1-2", 3, 2);
addPersoonlijkeScore("Hector", "W2D2-1", 4, 3);
addPersoonlijkeScore("Hector", "W2D2-2", 1, 2);
addPersoonlijkeScore("Hector", "W2D2-3", 3, 2);
addPersoonlijkeScore("Hector", "W2D3-1", 3, 1);
addPersoonlijkeScore("Hector", "W2D3-2", 4, 2);
addPersoonlijkeScore("Hector", "W2D3-3", 4, 2);
addPersoonlijkeScore("Hector", "W2D4-1", 2, 4);
addPersoonlijkeScore("Hector", "W2D4-2", 4, 1);
addPersoonlijkeScore("Hector", "W2D4-3", 3, 2);
addPersoonlijkeScore("Hector", "W2D5 - Project - Filmzoeker", 4, 1);
addPersoonlijkeScore("Hector", "W3D1-1", 1, 1);
addPersoonlijkeScore("Hector", "W3D1-2", 1, 4);
addPersoonlijkeScore("Hector", "W3D1-3", 3, 2);
addPersoonlijkeScore("Hector", "W3D1-4", 4, 3);
addPersoonlijkeScore("Hector", "W3D2-1", 1, 3);
addPersoonlijkeScore("Hector", "W3D2-2", 4, 3);
addPersoonlijkeScore("Hector", "W3D2-3", 2, 1);
addPersoonlijkeScore("Hector", "W3D3-1", 4, 4);
addPersoonlijkeScore("Hector", "W3D3-2", 3, 1);
addPersoonlijkeScore("Hector", "W3D3-3", 2, 4);
addPersoonlijkeScore("Hector", "W3D3-4", 4, 1);
addPersoonlijkeScore("Hector", "W3D4-1", 3, 4);
addPersoonlijkeScore("Hector", "W3D4-2", 1, 4);
addPersoonlijkeScore("Hector", "W3D5 - Project - Todo-List", 2, 4);
addPersoonlijkeScore("Hector", "W4D2-1", 1, 1);
addPersoonlijkeScore("Hector", "W4D2-2", 2, 1);
addPersoonlijkeScore("Hector", "W4D2-3", 3, 3);
addPersoonlijkeScore("Hector", "W4D2-4", 1, 3);
addPersoonlijkeScore("Hector", "W4D3-1", 3, 3);
addPersoonlijkeScore("Hector", "W4D3-2", 1, 4);
addPersoonlijkeScore("Hector", "W4D3-3", 3, 1);
addPersoonlijkeScore("Hector", "W4D3-4", 1, 3);
addPersoonlijkeScore("Hector", "W4D3-5", 1, 2);
addPersoonlijkeScore("Hector", "W4D3 - Project - Next-Level CSS", 3, 1);
addPersoonlijkeScore("Hector", "W5D4-1", 3, 4);
addPersoonlijkeScore("Hector", "W5D5 - Project - Lil_Playlist", 3, 1);
addPersoonlijkeScore("Hector", "W6D1-1", 1, 1);
addPersoonlijkeScore("Hector", "W6D2-1", 4, 2);
addPersoonlijkeScore("Hector", "W6D2 - Project - Eindopdracht", 2, 4);
addPersoonlijkeScore("Martina", "SCRUM", 1, 1);
addPersoonlijkeScore("Martina", "W1D1-1", 4, 1);
addPersoonlijkeScore("Martina", "W1D2-1", 3, 3);
addPersoonlijkeScore("Martina", "W1D2-2", 2, 1);
addPersoonlijkeScore("Martina", "W1D2-3", 2, 1);
addPersoonlijkeScore("Martina", "W1D2-4", 4, 2);
addPersoonlijkeScore("Martina", "W1D2-5", 3, 4);
addPersoonlijkeScore("Martina", "W1D3-1", 3, 4);
addPersoonlijkeScore("Martina", "W1D3-2", 2, 1);
addPersoonlijkeScore("Martina", "W1D3-4", 3, 2);
addPersoonlijkeScore("Martina", "W1D3-5", 1, 1);
addPersoonlijkeScore("Martina", "W1D3 - Project - Guess-the-number", 2, 2);
addPersoonlijkeScore("Martina", "W1D4-1", 4, 2);
addPersoonlijkeScore("Martina", "W1D4 - Project - Kleurentoggle", 1, 3);
addPersoonlijkeScore("Martina", "W1D5 - Project - Galgje", 1, 4);
addPersoonlijkeScore("Martina", "W2D1-1", 1, 4);
addPersoonlijkeScore("Martina", "W2D1-2", 4, 2);
addPersoonlijkeScore("Martina", "W2D2-1", 4, 1);
addPersoonlijkeScore("Martina", "W2D2-2", 3, 3);
addPersoonlijkeScore("Martina", "W2D2-3", 3, 1);
addPersoonlijkeScore("Martina", "W2D3-1", 4, 2);
addPersoonlijkeScore("Martina", "W2D3-2", 3, 4);
addPersoonlijkeScore("Martina", "W2D3-3", 3, 3);
addPersoonlijkeScore("Martina", "W2D4-1", 1, 4);
addPersoonlijkeScore("Martina", "W2D4-2", 3, 4);
addPersoonlijkeScore("Martina", "W2D4-3", 3, 4);
addPersoonlijkeScore("Martina", "W2D5 - Project - Filmzoeker", 2, 4);
addPersoonlijkeScore("Martina", "W3D1-1", 1, 1);
addPersoonlijkeScore("Martina", "W3D1-2", 3, 3);
addPersoonlijkeScore("Martina", "W3D1-3", 3, 1);
addPersoonlijkeScore("Martina", "W3D1-4", 3, 2);
addPersoonlijkeScore("Martina", "W3D2-1", 1, 2);
addPersoonlijkeScore("Martina", "W3D2-2", 2, 4);
addPersoonlijkeScore("Martina", "W3D2-3", 3, 1);
addPersoonlijkeScore("Martina", "W3D3-1", 1, 4);
addPersoonlijkeScore("Martina", "W3D3-2", 4, 1);
addPersoonlijkeScore("Martina", "W3D3-3", 3, 3);
addPersoonlijkeScore("Martina", "W3D3-4", 2, 3);
addPersoonlijkeScore("Martina", "W3D4-1", 4, 4);
addPersoonlijkeScore("Martina", "W3D4-2", 3, 1);
addPersoonlijkeScore("Martina", "W3D5 - Project - Todo-List", 2, 3);
addPersoonlijkeScore("Martina", "W4D2-1", 3, 4);
addPersoonlijkeScore("Martina", "W4D2-2", 1, 2);
addPersoonlijkeScore("Martina", "W4D2-3", 3, 4);
addPersoonlijkeScore("Martina", "W4D2-4", 4, 1);
addPersoonlijkeScore("Martina", "W4D3-1", 2, 4);
addPersoonlijkeScore("Martina", "W4D3-2", 1, 3);
addPersoonlijkeScore("Martina", "W4D3-3", 2, 4);
addPersoonlijkeScore("Martina", "W4D3-4", 4, 1);
addPersoonlijkeScore("Martina", "W4D3-5", 3, 2);
addPersoonlijkeScore("Martina", "W4D3 - Project - Next-Level CSS", 3, 4);
addPersoonlijkeScore("Martina", "W5D4-1", 1, 4);
addPersoonlijkeScore("Martina", "W5D5 - Project - Lil_Playlist", 1, 1);
addPersoonlijkeScore("Martina", "W6D1-1", 2, 1);
addPersoonlijkeScore("Martina", "W6D2-1", 1, 4);
addPersoonlijkeScore("Martina", "W6D2 - Project - Eindopdracht", 1, 4);
addPersoonlijkeScore("Maurits", "SCRUM", 3, 4);
addPersoonlijkeScore("Maurits", "W1D1-1", 4, 3);
addPersoonlijkeScore("Maurits", "W1D2-1", 2, 2);
addPersoonlijkeScore("Maurits", "W1D2-2", 1, 4);
addPersoonlijkeScore("Maurits", "W1D2-3", 2, 2);
addPersoonlijkeScore("Maurits", "W1D2-4", 3, 1);
addPersoonlijkeScore("Maurits", "W1D2-5", 2, 3);
addPersoonlijkeScore("Maurits", "W1D3-1", 2, 4);
addPersoonlijkeScore("Maurits", "W1D3-2", 2, 2);
addPersoonlijkeScore("Maurits", "W1D3-4", 2, 2);
addPersoonlijkeScore("Maurits", "W1D3-5", 1, 3);
addPersoonlijkeScore("Maurits", "W1D3 - Project - Guess-the-number", 1, 1);
addPersoonlijkeScore("Maurits", "W1D4-1", 3, 4);
addPersoonlijkeScore("Maurits", "W1D4 - Project - Kleurentoggle", 4, 1);
addPersoonlijkeScore("Maurits", "W1D5 - Project - Galgje", 3, 2);
addPersoonlijkeScore("Maurits", "W2D1-1", 1, 1);
addPersoonlijkeScore("Maurits", "W2D1-2", 2, 3);
addPersoonlijkeScore("Maurits", "W2D2-1", 1, 2);
addPersoonlijkeScore("Maurits", "W2D2-2", 4, 1);
addPersoonlijkeScore("Maurits", "W2D2-3", 2, 2);
addPersoonlijkeScore("Maurits", "W2D3-1", 2, 2);
addPersoonlijkeScore("Maurits", "W2D3-2", 3, 3);
addPersoonlijkeScore("Maurits", "W2D3-3", 2, 1);
addPersoonlijkeScore("Maurits", "W2D4-1", 1, 3);
addPersoonlijkeScore("Maurits", "W2D4-2", 3, 2);
addPersoonlijkeScore("Maurits", "W2D4-3", 3, 3);
addPersoonlijkeScore("Maurits", "W2D5 - Project - Filmzoeker", 3, 1);
addPersoonlijkeScore("Maurits", "W3D1-1", 4, 4);
addPersoonlijkeScore("Maurits", "W3D1-2", 1, 3);
addPersoonlijkeScore("Maurits", "W3D1-3", 1, 4);
addPersoonlijkeScore("Maurits", "W3D1-4", 1, 2);
addPersoonlijkeScore("Maurits", "W3D2-1", 1, 4);
addPersoonlijkeScore("Maurits", "W3D2-2", 1, 1);
addPersoonlijkeScore("Maurits", "W3D2-3", 4, 3);
addPersoonlijkeScore("Maurits", "W3D3-1", 1, 1);
addPersoonlijkeScore("Maurits", "W3D3-2", 2, 1);
addPersoonlijkeScore("Maurits", "W3D3-3", 1, 3);
addPersoonlijkeScore("Maurits", "W3D3-4", 4, 1);
addPersoonlijkeScore("Maurits", "W3D4-1", 4, 4);
addPersoonlijkeScore("Maurits", "W3D4-2", 1, 3);
addPersoonlijkeScore("Maurits", "W3D5 - Project - Todo-List", 3, 4);
addPersoonlijkeScore("Maurits", "W4D2-1", 3, 1);
addPersoonlijkeScore("Maurits", "W4D2-2", 4, 4);
addPersoonlijkeScore("Maurits", "W4D2-3", 4, 1);
addPersoonlijkeScore("Maurits", "W4D2-4", 2, 3);
addPersoonlijkeScore("Maurits", "W4D3-1", 3, 1);
addPersoonlijkeScore("Maurits", "W4D3-2", 3, 2);
addPersoonlijkeScore("Maurits", "W4D3-3", 3, 4);
addPersoonlijkeScore("Maurits", "W4D3-4", 1, 3);
addPersoonlijkeScore("Maurits", "W4D3-5", 2, 1);
addPersoonlijkeScore("Maurits", "W4D3 - Project - Next-Level CSS", 2, 3);
addPersoonlijkeScore("Maurits", "W5D4-1", 1, 3);
addPersoonlijkeScore("Maurits", "W5D5 - Project - Lil_Playlist", 4, 2);
addPersoonlijkeScore("Maurits", "W6D1-1", 1, 3);
addPersoonlijkeScore("Maurits", "W6D2-1", 1, 4);
addPersoonlijkeScore("Maurits", "W6D2 - Project - Eindopdracht", 3, 3);
addPersoonlijkeScore("Rahima", "SCRUM", 2, 4);
addPersoonlijkeScore("Rahima", "W1D1-1", 3, 4);
addPersoonlijkeScore("Rahima", "W1D2-1", 2, 4);
addPersoonlijkeScore("Rahima", "W1D2-2", 1, 2);
addPersoonlijkeScore("Rahima", "W1D2-3", 1, 3);
addPersoonlijkeScore("Rahima", "W1D2-4", 1, 2);
addPersoonlijkeScore("Rahima", "W1D2-5", 1, 3);
addPersoonlijkeScore("Rahima", "W1D3-1", 1, 1);
addPersoonlijkeScore("Rahima", "W1D3-2", 2, 4);
addPersoonlijkeScore("Rahima", "W1D3-4", 1, 2);
addPersoonlijkeScore("Rahima", "W1D3-5", 2, 2);
addPersoonlijkeScore("Rahima", "W1D3 - Project - Guess-the-number", 3, 1);
addPersoonlijkeScore("Rahima", "W1D4-1", 4, 3);
addPersoonlijkeScore("Rahima", "W1D4 - Project - Kleurentoggle", 2, 4);
addPersoonlijkeScore("Rahima", "W1D5 - Project - Galgje", 3, 3);
addPersoonlijkeScore("Rahima", "W2D1-1", 2, 2);
addPersoonlijkeScore("Rahima", "W2D1-2", 3, 1);
addPersoonlijkeScore("Rahima", "W2D2-1", 1, 1);
addPersoonlijkeScore("Rahima", "W2D2-2", 1, 1);
addPersoonlijkeScore("Rahima", "W2D2-3", 4, 2);
addPersoonlijkeScore("Rahima", "W2D3-1", 1, 1);
addPersoonlijkeScore("Rahima", "W2D3-2", 1, 4);
addPersoonlijkeScore("Rahima", "W2D3-3", 4, 2);
addPersoonlijkeScore("Rahima", "W2D4-1", 4, 4);
addPersoonlijkeScore("Rahima", "W2D4-2", 4, 4);
addPersoonlijkeScore("Rahima", "W2D4-3", 2, 3);
addPersoonlijkeScore("Rahima", "W2D5 - Project - Filmzoeker", 3, 1);
addPersoonlijkeScore("Rahima", "W3D1-1", 1, 1);
addPersoonlijkeScore("Rahima", "W3D1-2", 1, 2);
addPersoonlijkeScore("Rahima", "W3D1-3", 2, 3);
addPersoonlijkeScore("Rahima", "W3D1-4", 2, 4);
addPersoonlijkeScore("Rahima", "W3D2-1", 3, 2);
addPersoonlijkeScore("Rahima", "W3D2-2", 1, 4);
addPersoonlijkeScore("Rahima", "W3D2-3", 2, 1);
addPersoonlijkeScore("Rahima", "W3D3-1", 3, 1);
addPersoonlijkeScore("Rahima", "W3D3-2", 4, 4);
addPersoonlijkeScore("Rahima", "W3D3-3", 1, 4);
addPersoonlijkeScore("Rahima", "W3D3-4", 2, 2);
addPersoonlijkeScore("Rahima", "W3D4-1", 1, 2);
addPersoonlijkeScore("Rahima", "W3D4-2", 3, 3);
addPersoonlijkeScore("Rahima", "W3D5 - Project - Todo-List", 2, 4);
addPersoonlijkeScore("Rahima", "W4D2-1", 2, 4);
addPersoonlijkeScore("Rahima", "W4D2-2", 4, 3);
addPersoonlijkeScore("Rahima", "W4D2-3", 3, 3);
addPersoonlijkeScore("Rahima", "W4D2-4", 4, 1);
addPersoonlijkeScore("Rahima", "W4D3-1", 2, 1);
addPersoonlijkeScore("Rahima", "W4D3-2", 1, 1);
addPersoonlijkeScore("Rahima", "W4D3-3", 2, 1);
addPersoonlijkeScore("Rahima", "W4D3-4", 2, 2);
addPersoonlijkeScore("Rahima", "W4D3-5", 3, 2);
addPersoonlijkeScore("Rahima", "W4D3 - Project - Next-Level CSS", 1, 2);
addPersoonlijkeScore("Rahima", "W5D4-1", 3, 3);
addPersoonlijkeScore("Rahima", "W5D5 - Project - Lil_Playlist", 2, 3);
addPersoonlijkeScore("Rahima", "W6D1-1", 4, 4);
addPersoonlijkeScore("Rahima", "W6D2-1", 1, 4);
addPersoonlijkeScore("Rahima", "W6D2 - Project - Eindopdracht", 4, 1);
addPersoonlijkeScore("Sandra", "SCRUM", 4, 1);
addPersoonlijkeScore("Sandra", "W1D1-1", 2, 4);
addPersoonlijkeScore("Sandra", "W1D2-1", 3, 4);
addPersoonlijkeScore("Sandra", "W1D2-2", 3, 2);
addPersoonlijkeScore("Sandra", "W1D2-3", 3, 4);
addPersoonlijkeScore("Sandra", "W1D2-4", 3, 1);
addPersoonlijkeScore("Sandra", "W1D2-5", 4, 3);
addPersoonlijkeScore("Sandra", "W1D3-1", 1, 1);
addPersoonlijkeScore("Sandra", "W1D3-2", 1, 1);
addPersoonlijkeScore("Sandra", "W1D3-4", 3, 3);
addPersoonlijkeScore("Sandra", "W1D3-5", 4, 3);
addPersoonlijkeScore("Sandra", "W1D3 - Project - Guess-the-number", 2, 4);
addPersoonlijkeScore("Sandra", "W1D4-1", 3, 2);
addPersoonlijkeScore("Sandra", "W1D4 - Project - Kleurentoggle", 1, 3);
addPersoonlijkeScore("Sandra", "W1D5 - Project - Galgje", 3, 3);
addPersoonlijkeScore("Sandra", "W2D1-1", 4, 1);
addPersoonlijkeScore("Sandra", "W2D1-2", 4, 3);
addPersoonlijkeScore("Sandra", "W2D2-1", 3, 4);
addPersoonlijkeScore("Sandra", "W2D2-2", 2, 3);
addPersoonlijkeScore("Sandra", "W2D2-3", 4, 3);
addPersoonlijkeScore("Sandra", "W2D3-1", 1, 2);
addPersoonlijkeScore("Sandra", "W2D3-2", 3, 2);
addPersoonlijkeScore("Sandra", "W2D3-3", 2, 2);
addPersoonlijkeScore("Sandra", "W2D4-1", 1, 3);
addPersoonlijkeScore("Sandra", "W2D4-2", 2, 4);
addPersoonlijkeScore("Sandra", "W2D4-3", 2, 2);
addPersoonlijkeScore("Sandra", "W2D5 - Project - Filmzoeker", 2, 4);
addPersoonlijkeScore("Sandra", "W3D1-1", 3, 3);
addPersoonlijkeScore("Sandra", "W3D1-2", 3, 4);
addPersoonlijkeScore("Sandra", "W3D1-3", 2, 4);
addPersoonlijkeScore("Sandra", "W3D1-4", 2, 2);
addPersoonlijkeScore("Sandra", "W3D2-1", 2, 4);
addPersoonlijkeScore("Sandra", "W3D2-2", 2, 3);
addPersoonlijkeScore("Sandra", "W3D2-3", 1, 2);
addPersoonlijkeScore("Sandra", "W3D3-1", 1, 2);
addPersoonlijkeScore("Sandra", "W3D3-2", 2, 2);
addPersoonlijkeScore("Sandra", "W3D3-3", 4, 4);
addPersoonlijkeScore("Sandra", "W3D3-4", 3, 2);
addPersoonlijkeScore("Sandra", "W3D4-1", 2, 3);
addPersoonlijkeScore("Sandra", "W3D4-2", 1, 1);
addPersoonlijkeScore("Sandra", "W3D5 - Project - Todo-List", 1, 2);
addPersoonlijkeScore("Sandra", "W4D2-1", 3, 3);
addPersoonlijkeScore("Sandra", "W4D2-2", 1, 1);
addPersoonlijkeScore("Sandra", "W4D2-3", 3, 4);
addPersoonlijkeScore("Sandra", "W4D2-4", 1, 4);
addPersoonlijkeScore("Sandra", "W4D3-1", 3, 1);
addPersoonlijkeScore("Sandra", "W4D3-2", 1, 3);
addPersoonlijkeScore("Sandra", "W4D3-3", 2, 4);
addPersoonlijkeScore("Sandra", "W4D3-4", 1, 4);
addPersoonlijkeScore("Sandra", "W4D3-5", 1, 3);
addPersoonlijkeScore("Sandra", "W4D3 - Project - Next-Level CSS", 3, 4);
addPersoonlijkeScore("Sandra", "W5D4-1", 1, 1);
addPersoonlijkeScore("Sandra", "W5D5 - Project - Lil_Playlist", 2, 2);
addPersoonlijkeScore("Sandra", "W6D1-1", 1, 4);
addPersoonlijkeScore("Sandra", "W6D2-1", 2, 3);
addPersoonlijkeScore("Sandra", "W6D2 - Project - Eindopdracht", 4, 1);
addPersoonlijkeScore("Wietske", "SCRUM", 1, 1);
addPersoonlijkeScore("Wietske", "W1D1-1", 4, 3);
addPersoonlijkeScore("Wietske", "W1D2-1", 1, 4);
addPersoonlijkeScore("Wietske", "W1D2-2", 1, 2);
addPersoonlijkeScore("Wietske", "W1D2-3", 2, 3);
addPersoonlijkeScore("Wietske", "W1D2-4", 2, 1);
addPersoonlijkeScore("Wietske", "W1D2-5", 3, 4);
addPersoonlijkeScore("Wietske", "W1D3-1", 1, 2);
addPersoonlijkeScore("Wietske", "W1D3-2", 1, 4);
addPersoonlijkeScore("Wietske", "W1D3-4", 2, 1);
addPersoonlijkeScore("Wietske", "W1D3-5", 3, 4);
addPersoonlijkeScore("Wietske", "W1D3 - Project - Guess-the-number", 2, 4);
addPersoonlijkeScore("Wietske", "W1D4-1", 2, 4);
addPersoonlijkeScore("Wietske", "W1D4 - Project - Kleurentoggle", 2, 3);
addPersoonlijkeScore("Wietske", "W1D5 - Project - Galgje", 3, 3);
addPersoonlijkeScore("Wietske", "W2D1-1", 3, 1);
addPersoonlijkeScore("Wietske", "W2D1-2", 4, 1);
addPersoonlijkeScore("Wietske", "W2D2-1", 2, 2);
addPersoonlijkeScore("Wietske", "W2D2-2", 2, 4);
addPersoonlijkeScore("Wietske", "W2D2-3", 3, 4);
addPersoonlijkeScore("Wietske", "W2D3-1", 2, 1);
addPersoonlijkeScore("Wietske", "W2D3-2", 1, 1);
addPersoonlijkeScore("Wietske", "W2D3-3", 2, 3);
addPersoonlijkeScore("Wietske", "W2D4-1", 1, 1);
addPersoonlijkeScore("Wietske", "W2D4-2", 2, 4);
addPersoonlijkeScore("Wietske", "W2D4-3", 4, 3);
addPersoonlijkeScore("Wietske", "W2D5 - Project - Filmzoeker", 2, 2);
addPersoonlijkeScore("Wietske", "W3D1-1", 1, 3);
addPersoonlijkeScore("Wietske", "W3D1-2", 4, 4);
addPersoonlijkeScore("Wietske", "W3D1-3", 4, 2);
addPersoonlijkeScore("Wietske", "W3D1-4", 1, 4);
addPersoonlijkeScore("Wietske", "W3D2-1", 3, 2);
addPersoonlijkeScore("Wietske", "W3D2-2", 1, 3);
addPersoonlijkeScore("Wietske", "W3D2-3", 2, 4);
addPersoonlijkeScore("Wietske", "W3D3-1", 1, 4);
addPersoonlijkeScore("Wietske", "W3D3-2", 3, 1);
addPersoonlijkeScore("Wietske", "W3D3-3", 1, 3);
addPersoonlijkeScore("Wietske", "W3D3-4", 3, 4);
addPersoonlijkeScore("Wietske", "W3D4-1", 3, 4);
addPersoonlijkeScore("Wietske", "W3D4-2", 4, 2);
addPersoonlijkeScore("Wietske", "W3D5 - Project - Todo-List", 2, 4);
addPersoonlijkeScore("Wietske", "W4D2-1", 3, 3);
addPersoonlijkeScore("Wietske", "W4D2-2", 2, 4);
addPersoonlijkeScore("Wietske", "W4D2-3", 1, 2);
addPersoonlijkeScore("Wietske", "W4D2-4", 4, 3);
addPersoonlijkeScore("Wietske", "W4D3-1", 2, 1);
addPersoonlijkeScore("Wietske", "W4D3-2", 1, 2);
addPersoonlijkeScore("Wietske", "W4D3-3", 1, 4);
addPersoonlijkeScore("Wietske", "W4D3-4", 3, 4);
addPersoonlijkeScore("Wietske", "W4D3-5", 4, 3);
addPersoonlijkeScore("Wietske", "W4D3 - Project - Next-Level CSS", 4, 2);
addPersoonlijkeScore("Wietske", "W5D4-1", 3, 1);
addPersoonlijkeScore("Wietske", "W5D5 - Project - Lil_Playlist", 4, 2);
addPersoonlijkeScore("Wietske", "W6D1-1", 1, 1);
addPersoonlijkeScore("Wietske", "W6D2-1", 2, 1);
addPersoonlijkeScore("Wietske", "W6D2 - Project - Eindopdracht", 1, 2);
addPersoonlijkeScore("Storm", "SCRUM", 1, 1);
addPersoonlijkeScore("Storm", "W1D1-1", 2, 2);
addPersoonlijkeScore("Storm", "W1D2-1", 2, 3);
addPersoonlijkeScore("Storm", "W1D2-2", 1, 3);
addPersoonlijkeScore("Storm", "W1D2-3", 1, 2);
addPersoonlijkeScore("Storm", "W1D2-4", 4, 3);
addPersoonlijkeScore("Storm", "W1D2-5", 3, 3);
addPersoonlijkeScore("Storm", "W1D3-1", 2, 3);
addPersoonlijkeScore("Storm", "W1D3-2", 1, 1);
addPersoonlijkeScore("Storm", "W1D3-4", 1, 1);
addPersoonlijkeScore("Storm", "W1D3-5", 2, 2);
addPersoonlijkeScore("Storm", "W1D3 - Project - Guess-the-number", 3, 4);
addPersoonlijkeScore("Storm", "W1D4-1", 4, 2);
addPersoonlijkeScore("Storm", "W1D4 - Project - Kleurentoggle", 3, 2);
addPersoonlijkeScore("Storm", "W1D5 - Project - Galgje", 4, 4);
addPersoonlijkeScore("Storm", "W2D1-1", 2, 4);
addPersoonlijkeScore("Storm", "W2D1-2", 3, 2);
addPersoonlijkeScore("Storm", "W2D2-1", 4, 4);
addPersoonlijkeScore("Storm", "W2D2-2", 2, 1);
addPersoonlijkeScore("Storm", "W2D2-3", 1, 1);
addPersoonlijkeScore("Storm", "W2D3-1", 2, 3);
addPersoonlijkeScore("Storm", "W2D3-2", 3, 4);
addPersoonlijkeScore("Storm", "W2D3-3", 3, 2);
addPersoonlijkeScore("Storm", "W2D4-1", 3, 4);
addPersoonlijkeScore("Storm", "W2D4-2", 4, 3);
addPersoonlijkeScore("Storm", "W2D4-3", 2, 1);
addPersoonlijkeScore("Storm", "W2D5 - Project - Filmzoeker", 4, 1);
addPersoonlijkeScore("Storm", "W3D1-1", 2, 1);
addPersoonlijkeScore("Storm", "W3D1-2", 2, 2);
addPersoonlijkeScore("Storm", "W3D1-3", 1, 2);
addPersoonlijkeScore("Storm", "W3D1-4", 2, 3);
addPersoonlijkeScore("Storm", "W3D2-1", 1, 4);
addPersoonlijkeScore("Storm", "W3D2-2", 3, 3);
addPersoonlijkeScore("Storm", "W3D2-3", 3, 4);
addPersoonlijkeScore("Storm", "W3D3-1", 3, 4);
addPersoonlijkeScore("Storm", "W3D3-2", 1, 2);
addPersoonlijkeScore("Storm", "W3D3-3", 3, 1);
addPersoonlijkeScore("Storm", "W3D3-4", 3, 1);
addPersoonlijkeScore("Storm", "W3D4-1", 2, 4);
addPersoonlijkeScore("Storm", "W3D4-2", 3, 4);
addPersoonlijkeScore("Storm", "W3D5 - Project - Todo-List", 3, 2);
addPersoonlijkeScore("Storm", "W4D2-1", 2, 1);
addPersoonlijkeScore("Storm", "W4D2-2", 3, 3);
addPersoonlijkeScore("Storm", "W4D2-3", 2, 2);
addPersoonlijkeScore("Storm", "W4D2-4", 3, 4);
addPersoonlijkeScore("Storm", "W4D3-1", 3, 4);
addPersoonlijkeScore("Storm", "W4D3-2", 2, 3);
addPersoonlijkeScore("Storm", "W4D3-3", 1, 1);
addPersoonlijkeScore("Storm", "W4D3-4", 3, 1);
addPersoonlijkeScore("Storm", "W4D3-5", 2, 3);
addPersoonlijkeScore("Storm", "W4D3 - Project - Next-Level CSS", 4, 1);
addPersoonlijkeScore("Storm", "W5D4-1", 2, 2);
addPersoonlijkeScore("Storm", "W5D5 - Project - Lil_Playlist", 1, 2);
addPersoonlijkeScore("Storm", "W6D1-1", 4, 4);
addPersoonlijkeScore("Storm", "W6D2-1", 1, 1);
addPersoonlijkeScore("Storm", "W6D2 - Project - Eindopdracht", 3, 3);

export default scores;
